### ISSUE TITLE
Error with "Ignore hidden layers" checked. 

### ISSUE THREAD

**Issue by matejxxx** [jleclanche/inkscape-spine-exporter#3]
Error with "Ignore hidden layers" checked. 
If "Ignore hidden layers"  is not checked it is working fine.
System:MacOS Inkspace ver.:0.91

```pytb
Traceback (most recent call last):
 File "spine_exporter.py", line 279, in <module>
   effect.affect()
 File "/MyApps/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex.py", line 268, in affect
    self.effect()
  File "spine_exporter.py", line 242, in effect
    style = parse_css_style(layer.attrib.get("style", ""))
  File "spine_exporter.py", line 26, in parse_css_style
    k, v = directive.split(":")
 ValueError: need more than 1 value to unpack
```

**Comment by jleclanche** [comment]
Did you check in master? I think this was fixed in https://github.com/jleclanche/inkscape-spine-exporter/commit/225d2f848f2570cf0a9dd7b4040c0f1494694f7b

**Comment by matejxxx** [comment]
OK! I had old version!
Great work! Thx.

Also can you add/change in documentation something like:
Copy spine_exporter.inx and spine_exporter.py in Inkscape map 
".../Inkscape.app/Contents/Resources/share/inkscape/extensions"

**Comment by jleclanche** [comment]
Will do, thanks.
